<h2>Form Bantuan Pandemi</h2>

<?php echo $this->tag->form("transaksi/createbantuan");?>

    <div class="form-group">
        <label for="nama">Nama Pemberi Bantuan</label>
        <?php echo $this->tag->textField(["nama", "class" => "form-control", "placeholder" => "Nama"]); ?>
    </div>

    <h4>Jenis Bantuan</h4>

    <div class="form-group">
        <label for="uang">Uang Tunai</label>
        <?php echo $this->tag->textField(["uang", "class" => "form-control", "placeholder" => "Nominal"]); ?>
    </div>

    <div class="form-group">
        <label for="bahanmakanan">Bahan Makanan</label>
        <?php echo $this->tag->textField(["bahanmakanan", "class" => "form-control", "placeholder" => "Nama Bahan Makanan"]); ?>
    </div>

    <div class="form-group">
        <label for="obat">Obat</label>
        <?php echo $this->tag->textField(["obat", "class" => "form-control", "placeholder" => "Nama Obat"]); ?>
    </div>

    <div class="form-group">
        <label for="dll">Dll</label>
        <?php echo $this->tag->textField(["dll", "class" => "form-control", "placeholder" => "Nama Barang"]); ?>
    </div>

    <div class="form-group">
        <?php echo $this->tag->submitButton(["Submit", "class" => "btn btn-primary"]); ?>
    </div>

</form>