<div class="page-header">
    <h1>List Bantuan Bantuan Pandemi!</h1>
</div>

<table class="table">
    <thead>
        <tr>
            <td>
                <?php
                echo $this->tag->linkTo ([
                    "transaksi/uang","class" => "btn btn-primary",
                    "Uang"]
                );?>
                <?php
                echo $this->tag->linkTo ([
                    "transaksi/bahanmakanan","class" => "btn btn-primary",
                    "Bahan Makanan"]
                );?>
                <?php
                echo $this->tag->linkTo ([
                    "transaksi/obat","class" => "btn btn-primary",
                    "Obat"]
                );?>
                <?php
                echo $this->tag->linkTo ([
                    "transaksi/dll","class" => "btn btn-primary",
                    "Dll"]
                );?>
            </td>
            <td>
                <?php
                echo $this->tag->linkTo ([
                    "transaksi/form","class" => "btn btn-secondary",
                    "Beri Bantuan!"]
                );?>
            </td>
        </tr>
    </thead>
</table>
<div>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <td>Nama Pemberi</td>
            <td>Bantuan</td>
        </tr>
    </thead>
    <?php foreach($transaksi as $data){?>
        <tr>
            <td>
                <?php echo $data->nama; ?>
            </td>
            <td>
                <?php
                    if($data->id_kategori == "1"){
                        echo "Rp.".number_format($data->bantuan, 0, ",", ".").",-"; 
                    } else {
                        echo $data->bantuan;
                    }
                ?>
            </td>
        </tr>
    <?php } ?>
    
</table>
</div>